### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by rgilsbach** [deeptools/HiCBrowser#17] opened 2017-11-04 10:22 UTC
![unbenannt](https://user-images.githubusercontent.com/26813385/32404578-397c8a72-c152-11e7-8c4d-374565689f64.PNG)

By chance "image not found" appears. Sliding the window slightly mostly helps...

**Comment by bgruening** [comment] 2017-11-04 10:25
Did this appear after a few minutes waiting? It can be that the webserber times-out and then you see this image, reloading should help in this case.

**Comment by rgilsbach** [comment] 2017-11-04 15:52
Possibly, reloading did not help. This could also be a browser problem not reloading the page correctly…

 

 

 

Von: Björn Grüning [mailto:notifications@github.com] 
Gesendet: Samstag, 4. November 2017 11:26
An: maxplanck-ie/HiCBrowser <HiCBrowser@noreply.github.com>
Cc: rgilsbach <ralf.gilsbach@pharmakol.uni-freiburg.de>; Author <author@noreply.github.com>
Betreff: Re: [maxplanck-ie/HiCBrowser] Image not found (#17)

 

Did this appear after a few minutes waiting? It can be that the webserber times-out and then you see this image, reloading should help in this case.

**Comment by fidelram** [comment] 2017-11-04 19:27
This problem happens when there is a problem with the file being plotted. In the log file of the server the problem can be identified. Usually a bigwig file is not valid. Other reason for the image not being shown is that the configuration file contains a `skip=True`which is used to skip tracks without commenting them.

**Comment by vivekbhr** [comment] 2017-11-07 10:42
Usually because of an issue with bigwig files.. sometimes the problem is fixed by either zoomin/out or by removing the old images..

**Closed** 2017-11-13 20:12 UTC
